version: '3.9'

services:
  # Main application
  app:
    build:
      context: ./app
    container_name: owasp-demo-app
    env_file:
      - ./app/.env
    restart: always
    # Expose the app on port 3000
    ports:
      - '3000:3000'
    networks:
      app-db:

  db:
    image: postgres:latest
    container_name: owasp-demo-postgres
    env_file:
      - ./app/.env
    restart: always
    # Expose the db on port 15432 (only meant for db inspection from the host using `psql` or an admin tool)
    ports:
      - '15432:5432'
    networks:
      app-db:

  # A random 3rd party app for CORS demo
  third-party:
    build:
      context: ./third-party
    container_name: owasp-demo-third-party
    restart: always
    # Expose the app on port 400
    ports:
      - '4000:4000'

networks:
  app-db:
