version: "3.9"

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: owasp-demo-app
    env_file:
      - .env
    restart: always
    # Expose the app on port 3001
    ports:
      - "3001:3000"
    networks:
      app-postgres:

  postgres:
    image: postgres:latest
    container_name: owasp-demo-postgres
    env_file:
      - .env
    restart: always
    # Expose the db on port 15432 (only meant for db inspection from the host using `psql` or an admin tool)
    ports:
      - "15432:5432"
    networks:
      app-postgres:

networks:
  app-postgres: